version: "3.5"

services: 
  athena:
    container_name: athena-main
    networks: 
        - Athena_network
    build: .
    depends_on: 
      - athena-rds
      - standalone 
    volumes:
      - ./Athena:/Athena
    entrypoint: python Athena/wake.py

  athena-rds:
    container_name: athena-rds
    networks: 
        - Athena_network
    image: redis:7.0-alpine
    ports:
      - '6370:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  etcd:
    container_name: milvus-etcd
    networks: 
        - Athena_network
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    container_name: milvus-etcd

  minio:
    container_name: milvus-minio
    networks: 
        - Athena_network
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    container_name: milvus-mio

  standalone:
    container_name: milvus-standalone
    networks: 
        - Athena_network
    image: milvusdb/milvus:v2.2.2
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
    depends_on:
      - "etcd"
      - "minio"
    container_name: milvus-main


networks:
  Athena_network:

